service: proyectofinal

custom:
  serverless-offline:
    host: 0.0.0.0

frameworkVersion: '2'

plugins:
 - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: dev
  region: us-west-2

functions:
  postales:
    handler: handler.generic
    events:
      - httpApi:
          path: /
          method: ANY
      - httpApi:
          path: /{proxy+}
          method: ANY